spring:
  application:
    name: portal-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/ezaga"
    username: "root"
    password: "pass"
  logging:
    level:
      org:
        hibernate: DEBUG
#  logging.level.org.springframework.boot=DEBUG