spring:
  application:
    name: portal-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/ezaga"
    username: "root"
    password: "pass"
  logging:
    level:
      org:
        hibernate: DEBUG
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "tanakamadondo2@gmail.com"
    password: "xbwq psoi ugkx besw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
